[project]
name = "nanovlm"
version = "0.1.0"
description = ""
authors = [
    {name = "simo.brazzo@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "click (==8.1.7)",
    "cuda-python (==11.8.3)",
    "onnxruntime-gpu (==1.21.1)",
    "scikit-image (==0.22.0)",
    "openpyxl (==3.1.5)",
    "setuptools (>=78.1.0,<79.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "scikit-learn (>=1.6.1,<2.0.0)",
    "imgaug (>=0.4.0,<0.5.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "timm (>=1.0.15,<2.0.0)",
    "tensorboard (>=2.19.0,<3.0.0)",
    "torch (>=2.6.0,<3.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "onnxsim (>=0.4.36,<0.5.0)",
    "python-multipart (>=0.0.20,<0.0.21)",
    "flask (>=3.1.0,<4.0.0)",
    "datasets (>=3.6.0,<4.0.0)",
    "transformers (>=4.52.3,<5.0.0)",
    "optimum (>=1.26.1,<2.0.0)",
    "wandb (>=0.21.0,<0.22.0)",
    "onnxconverter-common (>=1.15.0,<2.0.0)",
]

[build-system]
requires = ["setuptools>=78"]
build-backend = "setuptools.build_meta"

[[tool.uv.index]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-gpu" }
torchvision = { index = "pytorch-gpu" }

[tool.uv]
package = false
